### ISSUE TITLE
support qAttached

### ISSUE THREAD

**Issue by froydnj** [luser/rust-gdb-remote-protocol#10]
This will at least be useful for minidump debugging.

**Comment by luser** [comment]
I'm curious as to whether you can run `gdbserver` on a core file and if so what the network traffic looks like. That might be a good thing to aim for parity with.

**Comment by tromey** [comment]
> I'm curious as to whether you can run gdbserver on a core file and if so what the network traffic looks like.

It's not built in but it was done once: https://lists.fedorahosted.org/pipermail/crash-catcher/2010-December/001441.html

I'm not sure if the code is available anywhere but you could write Jan to ask him.  However it is probably simpler to just wire it all together and try it, since that'll have to be done anyway.

**Comment by tromey** [comment]
When I connect to the no-op server from gdb, `qAttached` is the last command before gdb goes off into the weeds.  This is maybe a spot where we can't allow a dummy implementation of the handler.

**Comment by luser** [comment]
This seem pretty straightforward though, maybe just:

 ```rust
enum ProcessType { Attached, Created }

trait Handler {
  //...
  fn handle_attached(&self) -> ProcessType
}
```

Then noop-server can just have `fn handle_attached(&self) -> ProcessType { ProcessType::Attached }` (feel free to choose a better name for that enum...)

**Comment by tromey** [comment]
Yeah.  Also I was thinking that perhaps the noop server should move to `examples`.

**Comment by luser** [comment]
> Yeah. Also I was thinking that perhaps the noop server should move to examples.

Oh yeah! I have no idea why I put it in bin, that's not very useful.

**Comment by tromey** [comment]
I implemented this but it didn't really help; I think perhaps the real problem is not indicating support for `qXfer:exec-file:read`.
