### ISSUE TITLE
support qOffsets

### ISSUE THREAD

**Issue by froydnj** [luser/rust-gdb-remote-protocol#11]
It's not super clear that we need this... @tromey, do you know if this is really necessary?  (The TODO list in `lib.rs` is also unclear on this point.)

**Comment by tromey** [comment]
gdb sends it during the initial connection, but I believe it is fine to simply say it is not supported.

**Comment by luser** [comment]
I surveyed all the stuff that gdb sent in a simple gdbserver session (pcap file is on the wiki) and tried to filter out things that seemed obviously unnecessary, but I clearly wasn't sure about everything. [The docs](https://sourceware.org/gdb/onlinedocs/gdb/General-Query-Packets.html#index-section-offsets_002c-remote-request) don't *explicitly* say it's OK to return an empty response, so it's hard to say. I guess if we support `qXfer:libraries:read` we can just provide the library load addresses there and this isn't necessary?

**Comment by tromey** [comment]
That seems to be a bug in the docs.  gdbserver does this:

```
w $qOffsets#4b
r $#00
```

(That's the remote logging format, "w" means "gdb wrote it" and "r" means "reply from gdbserver.)

It'd be good to collect the various doc bugs and report them to gdb as well.

**Comment by tromey** [comment]
> I guess if we support qXfer:libraries:read we can just provide the library load addresses there and this isn't necessary?

I think so, see https://sourceware.org/bugzilla/show_bug.cgi?id=15696 and the threads it links to.

**Comment by tromey** [comment]
Filed https://sourceware.org/bugzilla/show_bug.cgi?id=22633 for the doc bug.

**Comment by tromey** [comment]
Aha, the overview says that any command can have an empty response.  https://sourceware.org/gdb/onlinedocs/gdb/Overview.html#Overview

**Comment by tromey** [comment]
I think we should not bother with `qOffsets`.  gdbserver only implements it for one very obscure case.
