### ISSUE TITLE
support vKill packet

### ISSUE THREAD

**Issue by froydnj** [luser/rust-gdb-remote-protocol#13]
We already support the `k` packet; this is simply a more sophisticated version that enables specifying the process ID to target.  GDB will also use this packet when we indicate that multiprocess extensions are supported.

**Comment by tromey** [comment]
One idea we discussed on irc was to only support multi-process; in which case we could drop the `k` packet and several others.

**Comment by luser** [comment]
I thought it might be simpler to support the single-process case at the start, but if we want to support multi-process eventually it's probably not any harder to just do that instead.
