### ISSUE TITLE
Migrate CI from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by luser** [luser/rust-gdb-remote-protocol#64]
[Travis CI has ended support for free CI for open source projects](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), so we should migrate CI to GitHub Actions. GitHub has [a migration guide](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions) that should be straightforward to follow, but given how simple the existing CI setup is, starting with [the `actions-rs` quickstart example](https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md) would also be reasonable.

cc @jD91mZM2

**Comment by jD91mZM2** [comment]
Sounds reasonable, especially actions-rs since it fits our needs perfectly. I can't take a look at it this week, but I can perform the migration eventually :smile:

**Comment by jD91mZM2** [comment]
I've always wanted to check out how GitHub actions work, but I've been using GitLab for all my personal projects. So this worked out perfectly. Thanks for the help finding `actions-rs`, I basically just copied their example :)
